projects = [[ 'GPUCompute.js', 'gpucompute.jpg', `I developed a system for doing computation on the GPU in the web browser. Using this I also developed a particle system demo which performs physics calculations on each particle every frame on the GPU. This allows it to support millions of particles. You can see the demo <a href=http://samcordingley.com/GPUCompute.js>here</a>.`],
            [ 'Sarah Powell Yoga', 'sarahpowellyoga.jpg', `I developed a website for a yoga instructor client. It was made so that all the content could be quickly and easily edited by the client. A version of it can be seen <a href=http://35.178.87.255>here</a>.`],
            [ 'Cryptoconomy', 'crypto.jpg','In development. Cryptoconomy is a website that shows cryptocurrency news on a globe, giving time and location context to the articles. The globe features a real-time accurate sunlight system, modelling the actual current position of the sun to light the globe correctly.'],
            [ 'Heatmap News', 'heatmap.jpg', 'Heatmap News is a website that displays the most important world news stories on a map of the Earth. It lets you quickly see what is happening in the world right now. The front-end was developed with HTML/CSS/JavaScript/jQuery while the back-end was developed with Python/Django. The website is no longer active but received press coverage <a href="https://goo.gl/kuZ1qZ">here</a>.'],
            [ 'Light Field Rendering', 'lightfield.jpg',`I wrote my MEng dissertation on "Light Field Rendering for Real-time Applications" and developed a system for capturing light fields of Autodesk Maya scenes with Pixar's RenderMan and rendering them in real-time within Unreal Engine 4. <a href="dissertation.pdf">Read the dissertation here.</a> See a demo <a href="https://www.youtube.com/watch?v=-S2_nrkbvHI&feature=youtu.be">here</a>.`],
            [ 'C++ Rasteriser', 'rasteriser.jpg',`I developed a rasterisation graphics engine using C++. It's features include shadows and bump mapping.`],
            [ 'C++ Raytracer', 'raytracer.jpg',`I developed a raytracer graphics engine using C++. It's features include textures, shadows, and reflections.`],
            [ 'Orange Render', 'orange.jpg', `I created a realistic orange material for Maya/Arnold.`],
            [ 'Robot 3D Model', 'robot.jpg',`I designed and created a complex 3D model of a robot. The model was created using Autodesk Maya.`],
            [ 'Dance Animation', 'animation.jpg',`I created an animation of a dancing robot using Autodesk Maya. You can watch the videos <a href=https://www.youtube.com/watch?v=zq4TXOm3G5M>here</a> and <a href=https://www.youtube.com/watch?v=sPlKOZ4w3UU>here</a>.`],
            [ 'Tomb of Terror', 'tombofterror.jpg',`I spent a year as the lead programmer of a group of seven developing a multiplayer virtual reality game for the Oculus Rift DK2 called Tomb of Terror. The game worked around an echolocation mechanic where sound was visualised as glowing waves propagating throughout the room. I built the echolocation mechanic using a combination of C# and GLSL within the Unity game engine. Click <a href="https://www.youtube.com/watch?v=sU5LFoEexTo">here</a> and <a href="https://www.youtube.com/watch?time_continue=17&v=CHCnagA5_CY">here</a> for videos demonstrating the sound vision shader. </p>`],
            [ 'MyEnvironment', 'myenv.jpg',`Worked with the Environment Agency to replace their 'What's in your backyard' service with a modern cross-platform mobile app. Specifically, I worked on the back-end system, providing environmental data for the app. I also helped implement Android specific features on the front-end. `],
            [ 'Freeze Box', 'freezebox.jpg',`I developed a game in 48 hours for the Ludum Dare game jam competition. The game is a platformer in which you control a box which freezes after 10 seconds. After the box has frozen a new box spawns, this allows you to progress through the level by positioning your boxes before the 10 seconds runs out. Download the game <a href=http://ludumdare.com/compo/ludum-dare-27/?action=preview&uid=26905>here</a>.`]
          ];
